### ISSUE TITLE
Error Page does not appear on invaild URL on netlify deploy

### ISSUE THREAD

**Issue by OccultParrot** [savevsgames/React-Portfolio#1]
On deployed link, if I add a invalid extension such as `https://quiet-hotteok-ca264a.netlify.app/test` it just shows the following screen
![this](https://github.com/user-attachments/assets/e2dc8dbf-7cf1-46c0-9bf7-6871a91de1c2)

**Comment by savevsgames** [comment]
Just checked it. It works.

The web service is  unpaid - so sometimes render takes its time spinning up free services.

**Comment by OccultParrot** [comment]
Oooooooooooh, ok! Figured I would let you know!
